### ISSUE TITLE
rotz function in registration.m not found, phased array toolbox probably needed?

### ISSUE THREAD

**Issue by stowerslab** [nerf-common/whole-brain-fUS#2]

**Comment by stowerslab** [comment]
for rotating images for registration

**Comment by gabmontaldo** [comment]
Yes rotx roty and rotz they are part of a toolbox but there are  open versions for example here:
https://github.com/petercorke/spatialmath-matlab

**Comment by gabmontaldo** [comment]
Here my version of the 3 functions:

function M=rotx(alfa)
c=cos(alfa*pi/180);
s=sin(alfa*pi/180);
M = [ 1   0   0
        0   c  -s
        0   s   c ];
end


function M=roty(alfa)
c=cos(alfa*pi/180);
s=sin(alfa*pi/180);
M = [ c   0   s
        0   1   0
       -s   0   c ];
end

function M=rotz(alfa)
c=cos(alfa*pi/180);
s=sin(alfa*pi/180);
M = [ c  -s  0
        s   c  0
        0   0  1];
end

**Comment by stowerslab** [comment]
thanks gab, I did see that there were open sourced versions, but I was unsure about using them as there were some comments that the phased array toolbox versions work in degrees while the open source versions work in radians. I took a look and saw that by default the link you sent works with radians unless the degree argument is passed to them, I tried searching the registration scripts to see what version would work but was unable to sort it out, thus it would be great if the authors could clarify
